### ISSUE TITLE
HA update broke Remootio integration again

### ISSUE THREAD

**Issue by CCupler** [sam43434/remootio#11]
Updated to latest versions: HAOS 9.5, HA Core 2023.3.5 
Remootio integration is again 'broken' - will not reload, have no control over, or status of, garage door. 

Remootio version 839e575

Log entry: 
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/remootio/utils.py:83
Integration: Remootio
First occurred: 9:55:43 PM (1 occurrences)
Last logged: 9:55:43 PM

Error setting up entry Remootio Device (Host: 192.168.20.10, S/N: 244cabd0a24cgrowgpwj) for remootio
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioremootio/remootioclient.py", line 318, in __initialize
    await self.__lifecycle.wait_for(lambda: self.connected)
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 296, in wait_for
    await self.wait()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 269, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/remootio/__init__.py", line 38, in async_setup_entry
    remootio_client: RemootioClient = await create_client(
  File "/config/custom_components/remootio/utils.py", line 83, in create_client
    result = await RemootioClient(
  File "/usr/local/lib/python3.10/site-packages/async_class.py", line 133, in __await__
    yield from self.__ainit__(*self._args, **self._kwargs).__await__()
  File "/usr/local/lib/python3.10/site-packages/aioremootio/remootioclient.py", line 290, in __ainit__
    await self.__initialize()
  File "/usr/local/lib/python3.10/site-packages/aioremootio/remootioclient.py", line 332, in __initialize
    raise RemootioClientError(self, "Failed to initialize this client.") from ex
aioremootio.errors.RemootioClientError: Failed to initialize this client. Host [192.168.20.10] SerialNumber [N/A] ApiVersion [N/A] State [State.OPEN]

**Comment by jwinston100** [comment]
I have HA core version 2023.6.0 running, and the Remootio integration works with this version, but after upgrading to the most recent version of core, 2023.7.2, the integration broke even with the previous hack which @yarafie had provided which had worked, https://github.com/sam43434/remootio/issues/7#issuecomment-1453075005
