### ISSUE TITLE
Integration is not loading correctly

### ISSUE THREAD

**Issue by fireheadman** [sam43434/remootio#26]
Getting this error in logs...

```
2024-06-25 13:12:46.433 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Front Gate for remootio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remootio/__init__.py", line 38, in async_setup_entry
    remootio_client: RemootioClient = await create_client(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remootio/utils.py", line 91, in create_client
    await _check_api_version(result)
  File "/config/custom_components/remootio/utils.py", line 34, in _check_api_version
    if api_version < EXPECTED_MINIMUM_API_VERSION:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

![image](https://github.com/sam43434/remootio/assets/19847195/4c0ba54b-87f0-41b5-b48f-e7e1f1366e56)

![image](https://github.com/sam43434/remootio/assets/19847195/c2934216-1646-41c0-84ea-896b08dddb2a)

**Comment by fireheadman** [comment]
![image](https://github.com/sam43434/remootio/assets/19847195/f8e1ac13-16a1-484c-8f3a-5f5fac3dd02e)
