### ISSUE TITLE
Intermittent problems with opening and closing

### ISSUE THREAD

**Issue by marioalfaro75** [sam43434/remootio#4]
Hi, Opening Garage door stops working intermittently. I can fix it by restarting Home Assistant.

IP address of remootio is fixed via MAC reservation.
I have the latest updates of HA, HACS and Remootio integration.

Below are logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/remootio/cover.py:119
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:46:52 am (14 occurrences)
Last logged: 9:08:27 am

[139832430129552] Sending of frame has been failed because connection to the device can't be established. Host [192.XXX.XXX.XXX] SerialNumber [c4XXXXXXXXXXXXXkt] ApiVersion [3] State [State.CLOSED]
[139832210920144] Sending of frame has been failed because connection to the device can't be established. Host [192.XXX.XXX.XXX] SerialNumber [c4XXXXXXXXXXXXXkt] ApiVersion [3] State [State.CLOSED]
[139832209339920] Sending of frame has been failed because connection to the device can't be established. Host [192.XXX.XXX.XXX] SerialNumber [c4XXXXXXXXXXXXXkt] ApiVersion [3] State [State.CLOSED]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/remootio/cover.py", line 119, in async_open_cover
    await self._remootio_client.trigger_open()
  File "/usr/local/lib/python3.10/site-packages/aioremootio/remootioclient.py", line 1354, in trigger_open
    await self.__trigger(ActionType.OPEN)
  File "/usr/local/lib/python3.10/site-packages/aioremootio/remootioclient.py", line 1250, in __trigger
    await self.__encrypt_and_send_frame(frame)
  File "/usr/local/lib/python3.10/site-packages/aioremootio/remootioclient.py", line 867, in __encrypt_and_send_frame
    await self.__send_frame(encrypted_frame, ws)
  File "/usr/local/lib/python3.10/site-packages/aioremootio/remootioclient.py", line 853, in __send_frame
    raise RemootioClientConnectionEstablishmentError(
aioremootio.errors.RemootioClientConnectionEstablishmentError: Sending of frame has been failed because connection to the device can't be established. Host [192.XXX.XXX.XXX] SerialNumber [c4XXXXXXXXXXXXXkt] ApiVersion [3] State [State.CLOSED]

**Comment by vical22** [comment]
I have the same issue. 
I have created automation to reload the entity every 12 hours, but it looks like the frequency becomes more often...
